apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvmongo
  labels:
    app: mongo
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
 
  hostPath:                    
    path: "/mongo/data"