apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvmongo
  namespace: default
  labels:
    app: mongo
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:                    
    path: "/mongo/data"