apiVersion: apps/v1
kind: Deployment                                          # 1
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate: 
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:                                               # 6
    metadata:
      labels:
        app: frontend                                  # 7
    spec:
      containers:
        - image: 999dockersyrov/frontend
          imagePullPolicy: Always                         # 8
          name: frontend
          ports:
            - containerPort: 3050