apiVersion: v1
kind: Service
metadata:
  labels:
    app: stats
  name: stats-svc
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 3001               # 3
      protocol: TCP          # 4
      targetPort: 3001
  selector:
    app: stats